namespace UiEditor.ViewModels;

public sealed record ThemePalette(
    string WindowBackground,
    string DialogBackground,
    string CardBackground,
    string CardBorderBrush,
    string PrimaryTextBrush,
    string SecondaryTextBrush,
    string CanvasBackground,
    string CanvasBorderBrush,
    string GridLineBrush,
    string EditPanelBackground,
    string EditPanelBorderBrush,
    string EditPanelButtonBackground,
    string EditPanelButtonBorderBrush,
    string EditPanelInputBackground,
    string EditPanelInputForeground,
    string ParameterEditBackgrundColor,
    string ParameterEditForeColor,
    string ParameterHoverColor,
    string ButtonBackColor,
    string ButtonHoverColor,
    string ButtonForeColor,
    string HeaderBadgeBackground,
    string HeaderBadgeForeground)
{
    public static ThemePalette Light { get; } = new(
        WindowBackground: "#F4F5F7",
        DialogBackground: "#d6d6e7",
        CardBackground: "#f3f3f3",
        CardBorderBrush: "#D5D9E0",
        PrimaryTextBrush: "#111827",
        SecondaryTextBrush: "#5E6777",
        CanvasBackground: "#FCFCFD",
        CanvasBorderBrush: "#C9CED8",
        GridLineBrush: "#E9EEF5",
        EditPanelBackground: "#3d6d9c",
        EditPanelBorderBrush: "#CBD5E1",
        EditPanelButtonBackground: "#F8FAFC",
        EditPanelButtonBorderBrush: "#CBD5E1",
        EditPanelInputBackground: "#FFFFFF",
        EditPanelInputForeground: "#000000",
        ParameterEditBackgrundColor: "#FFFFFF",
        ParameterEditForeColor: "#111827",
        ParameterHoverColor: "#BDBDBD",
        ButtonBackColor: "#cfdbe7",
        ButtonHoverColor: "#E2E8F0",
        ButtonForeColor: "#111827",
        HeaderBadgeBackground: "#FFFFFF",
        HeaderBadgeForeground: "#FFFFFF");

    public static ThemePalette Dark { get; } = new(
        WindowBackground: "#0B0B0C",
        DialogBackground: "#1F2937",
        CardBackground: "#111827",
        CardBorderBrush: "#374151",
        PrimaryTextBrush: "#F9FAFB",
        SecondaryTextBrush: "#9CA3AF",
        CanvasBackground: "#000000",
        CanvasBorderBrush: "#4B5563",
        GridLineBrush: "#2F343C",
        EditPanelBackground: "#1F2937",
        EditPanelBorderBrush: "#4B5563",
        EditPanelButtonBackground: "#374151",
        EditPanelButtonBorderBrush: "#4B5563",
        EditPanelInputBackground: "#374151",
        EditPanelInputForeground: "#F9FAFB",
        ParameterEditBackgrundColor: "#374151",
        ParameterEditForeColor: "#F9FAFB",
        ParameterHoverColor: "#60A5FA",
        ButtonBackColor: "#374151",
        ButtonHoverColor: "#4B5563",
        ButtonForeColor: "#F9FAFB",
        HeaderBadgeBackground: "#F9FAFB",
        HeaderBadgeForeground: "#111827");
}
